login_app/urls.py
from django.urls import path
from . import views

app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset_secret/<str:secret>/', views.password_reset_secret, name='password_reset_secret'),
    path('password_reset_form/', views.password_reset_form, name='password_reset_form'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

todo_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from . import views

app_name = "todo_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("change_status", views.change_status, name="change_status"),
    path("completed_todos/", views.completed_todos, name="completed_todos"),
    path("delete_todo/", views.delete_todo, name="delete_todo"),
    path("details", views.details, name="details"),
    path("pdf/", views.pdf, name="pdf"),
]

todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_app.urls")),
    path("accounts/", include("login_app.urls")),
]

login_app/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe

class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    secret = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.user} - {self.created_timestamp}"

todo_app/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    status = models.BooleanField(default=False)

    @classmethod
    def create(cls, user, text):
        todo = cls()
        todo.user = user
        todo.text = text
        todo.save()

    def toggleStatus(self):
        self.status = not self.status
        self.save()

    def __str__(self):
        return f"{self.text} - {self.status}"

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from phone_field import PhoneField
from django.db.models.signals import post_save
from django.dispatch import receiver


class User_Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    mobileNumber = PhoneField(
        blank=False, unique=False, help_text="Contact phone number"
    )
    RANK = (
        ("Gold", ("Gold membership")),
        ("Silver", ("Silver membership")),
        ("Basic", ("Basic membership")),
    )
    rank = models.CharField(max_length=32, choices=RANK, default="Basic")
    kappa = models.CharField(max_length=1)

    def __str__(self):
        return f"{self.user} - {self.mobileNumber}"

login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from . import models
import django_rq
from .messaging import email_message
from user_profile.models import User_Profile


def login(request):
    context = {}
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse("todo_app:index"))
        else:
            content = {"error": "Bad username or password."}

    return render(request, "login_app/login.html", context)


def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse("login_app:login"))


def password_reset(request):
    context = {}

    if request.method == "POST":
        email = request.POST["email"]
        user = User.objects.get(email=email)
        reset_request = models.PasswordResetRequest()
        reset_request.user = user
        reset_request.save()
        url = reverse(
            "login_app:password_reset_secret", args=[f"{reset_request.secret}"]
        )
        url = f'{request.scheme}://{request.META["HTTP_HOST"]}{url}'
        print(url)
        context = {"message": "Please click the link in the email we sent to you."}
        django_rq.enqueue(email_message, {"email_receiver": email, "reset_link": url})

    return render(request, "login_app/password_reset.html", context)


def password_reset_secret(request, secret):
    context = {"secret": secret}
    return render(request, "login_app/password_reset_form.html", context)


def password_reset_form(request):
    email = request.POST["email"]
    password = request.POST["password"]
    confirm_password = request.POST["confirm_password"]
    secret = request.POST["secret"]

    user = User.objects.get(email=email)
    reset_request = models.PasswordResetRequest.objects.get(user=user, secret=secret)
    if password == confirm_password:
        user.set_password(password)
        user.save()
        reset_request.save()
        return HttpResponseRedirect(reverse("login_app:login"))
    context = {"error": "Something went wrong, try again, don't screw up this time!"}
    return render(request, "login_app/password_reset_form.html", context)


def sign_up(request):
    context = {}
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        phone = request.POST["phone"]
        confirm_password = request.POST["confirm_password"]
        email = request.POST["email"]
        if password == confirm_password:
            return HttpResponseRedirect(reverse("login_app:login"))
        else:
            context = {"error": "Passwords did not match. Please try agian."}
    return render(request, "login_app/sign_up.html", context)


def delete_account(request):
    pass

todo_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, FileResponse
from django.urls import reverse
from .models import Todo
from django.contrib.auth.decorators import login_required
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch, cm
import io
import django_rq
from .downloadPdf import generate_pdf

# Create your views here.


@login_required
def index(request):
    if request.method == "POST":
        text = request.POST["text"]
        Todo.create(request.user, text)

    todos = Todo.objects.filter(status=False).filter(user=request.user)
    context = {"todos": todos}

    return render(request, "todo_app/index.html", context)


@login_required
def completed_todos(request):
    todos = Todo.objects.filter(status=True).filter(user=request.user)
    context = {"todos": todos}
    return render(request, "todo_app/completed_todos.html", context)


@login_required
def change_status(request):
    pk = request.POST["pk"]
    todo = get_object_or_404(Todo, pk=pk)
    todo.toggleStatus()
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


@login_required
def delete_todo(request):
    pk = request.POST["pk"]
    todo = get_object_or_404(Todo, pk=pk)
    todo.delete()
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


def details(request):
    pk = request.GET.get("pk")
    print(pk)
    todo = get_object_or_404(Todo, pk=pk)
    context = {"todo": todo}
    return render(request, "todo_app/details.html", context)


def pdf(request):
    # todos = Todo.objects.filter(user=request.user)
    buffer = django_rq.enqueue(generate_pdf)
    return FileResponse(buffer, as_attachment=True, filename="hello.pdf")

user_profile/views.py
from django.shortcuts import render

# Create your views here.

login_app/templates/login_app/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>

<body>
    <h1>Login</h1>
    <hr>
    <form action="{% url 'login_app:login' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <br>
        <input type="password" name="password" placeholder="Password">
        <br>
        <input type="submit" value="Login">
    </form>
    <hr>
    {% if error %}<p style="color:red">{{error}}</p> {% endif %}
    <a href="{% url 'login_app:sign_up' %}">Sign Up</a>
    <a href="{% url 'login_app:password_reset' %}">Request Password Reset</a>
</body>

</html>

login_app/templates/login_app/password_reset.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Request Password Request</title>
</head>

<body>
    <h1>Request Password Request</h1>
    <a href="{% url 'login_app:login' %}">Log In</a>
    <hr>
    <form action="{% url 'login_app:password_reset' %}" method="POST">
        {% csrf_token %}
        <input type="email" name="email" placeholder="Email">
        <br>
        <input type="submit" value="Reset password">
    </form>
    <hr>
    {% if message %}{{ message }}{% endif %}
</body>

</html>

login_app/templates/login_app/password_reset_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Please Set New Password</title>
</head>

<body>
    <h1>New Password</h1>
    <hr />
    <form action="{% url 'login_app:password_reset_form' %}" method="POST">
        {% csrf_token %}
        <input type="email" name="email" placeholder="Email Address">
        <input type="password" name="password" placeholder="Password">
        <input type="password" name="confirm_password" placeholder="Confirm Password">
        <input type="hidden" name="secret" value="{{ secret }}">
        <input type="submit" value="Set New Password">
    </form>
    <hr />
    {% if error %}{{ error }}{% endif %}
</body>

</html>

login_app/templates/login_app/sign_up.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign up</title>
</head>

<body>
    <h1>Sign up</h1>
    <hr>
    <form action="{% url 'login_app:sign_up'%}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="email" name="email" placeholder="Email">
        <input type="tel" name="phone" place="mobile number">
        <input type="password" name="password" placeholder="Password">
        <input type="password" name="confirm_password" placeholder="Cornfirm password">
        <input type="submit" value="Sign up">
    </form>
</body>

</html>

todo_app/templates/todo_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'todo_app/styles.css' %}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body>
    {% block content %}
    {% endblock %}
    {% block footer %}
    {% endblock %}
</body>

</html>

todo_app/templates/todo_app/completed_todos.html
{% extends 'todo_app/base.html' %}
{% block title %} Completed Todos {% endblock %}
{% block content %}
<h1>Completed Todos</h1>
<hr>
<ul>
    {% for todo in todos %}
    <li>
        <form action="{% url 'todo_app:change_status' %}" method="POST">
            {% csrf_token %}
            <input type="checkbox" name="checked" onclick="this.form.submit()" {%if todo.status%}checked{%endif%} />
            <input type="hidden" name="pk" value="{{ todo.pk }}">
            {{ todo.text }}
        </form>
    </li>
    {% endfor %}
</ul>
<hr>
<a href="{% url 'todo_app:index' %}">Todos</a>
{% endblock %}

todo_app/templates/todo_app/details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
</head>

<body>
    {{todo.text}}
</body>

</html>

todo_app/templates/todo_app/index.html
{% extends 'todo_app/base.html' %}
{% block title %} Todos {% endblock %}
{% block content %}
<h1>Todo</h1>
<p>Hello: {{ user.username }}</p>
<hr />
<ul>
  {% for todo in todos %}
  <li>
    <form action="{% url 'todo_app:change_status' %}" method="POST">
      {% csrf_token %}
      <input type="checkbox" name="checked" onclick="this.form.submit()" />
      <button formaction="{% url 'todo_app:delete_todo' %}">Delete</button>
      <input type="hidden" name="pk" value="{{ todo.pk }}" />
      <a href="{% url 'todo_app:details' %}?pk={{ todo.pk }}">{{ todo.text }}</a>
    </form>
  </li>
  {% endfor %}
</ul>
<hr />
<a href=" {% url 'todo_app:completed_todos' %}">Completed Todos</a>
<a href="{% url 'todo_app:pdf' %}">Pdf</a>
<form action="." method="POST">
  {% csrf_token %}
  <input type="text" name="text" placeholder="Write your todo item here!" />
  <button>create todo</button>
</form>
<a href="{% url 'login_app:logout' %}">Log out</a>
{% endblock %}